### PR TITLE
Make craftable using recipe from Taose fork

### PR DESCRIPTION
**Pull request by minertestdude**
This adds recipe for tool, so users can craft it.

[ ] collisions with other mods?
[ ] issues like excessive data? (Taose fork provides limited reporting using additional privs)

### CODE REVIEW

**Comment by thomasrudin** [comment]
Can this be packaged with a setting (default: off)?
I don't think it is a good idea to give this ability on everybody on a survival server:

* Inspect passwords on mesecons/digiline blocks
* Inspect missions/quests stored in node-metadata (with secret goals for example)

(sorry for the criticism, i know you just wanna help)

**Comment by minertestdude** [comment]
@thomasrudin Ok, so it falls under "excessive data". Then we should include Taose fork instead with updates from stock, because it adds priv checks and degrades reporting for normal user.

No, this should NOT be packaged with default:off, because this tool is very important for normal user - it shows node info to understand which block is used in constructions and shows light info, to improve farming.

Previously on survival server was other (but craftable) node inspection tool, who provided only necessary info, but it was replaced with uncraftable one.

**Comment by sofar** [comment]
This tool was designed to be an admin tool for debugging mods. I don't want to change that, because in my opinion it reveals too much data and is immersion breaking even if you restrict usage with privileges.

So, a recipe is fine, but by default it shouldn't be craftable.

**Comment by sofar** [comment]
Closing due to no update with requested changes.

**Pull request closed without merging**
